### PR TITLE
Use a version dependent sbt plugin

### LINKED ISSUE #2847: StewardPlugin.scala cannot be loaded by sbt < 1.3.0
Since https://github.com/scala-steward-org/scala-steward/pull/2533 `StewardPlugin.scala` cannot be loaded by sbt versions older than 1.3.0 (i.e sbt without Coursier integration) as can be seen in com-lihaoyi/scalatags which still uses sbt 1.2.8:
```
[info] 2022-12-21 20:06:37,126 INFO  ──────────── Steward com-lihaoyi/scalatags ────────────
[info] 2022-12-21 20:06:37,127 INFO  Check cache of com-lihaoyi/scalatags
[info] 2022-12-21 20:06:38,065 INFO  Clone scala-steward/scalatags
[info] 2022-12-21 20:06:39,254 INFO  Synchronize with com-lihaoyi/scalatags
[info] 2022-12-21 20:06:40,215 INFO  Refresh cache of com-lihaoyi/scalatags
[info] 2022-12-21 20:07:01,284 ERROR Steward com-lihaoyi/scalatags failed
[info] java.io.IOException: 'sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1
[info] [info] Loading global plugins from /home/frank/.sbt/1.0/plugins
[info] [info] Updating ProjectRef(uri("file:/home/frank/.sbt/1.0/plugins/"), "global-plugins")...
[info] [info] Done updating.
[info] [info] Compiling 1 Scala source to /home/frank/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:67:15: not found: value csrConfiguration
[info] [error]               csrConfiguration.value.authenticationByRepositoryId.toList
[info] [error]               ^
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:69:56: value headers is not a member of Any
[info] [error]             (headerKey, headerValue) <- authentication.headers
[info] [error]                                                        ^
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:70:35: type mismatch;
[info] [error]  found   : Any
[info] [error]  required: String
[info] [error]           } yield Resolver.Header(headerKey, headerValue)
[info] [error]                                   ^
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:70:46: type mismatch;
[info] [error]  found   : Any
[info] [error]  required: String
[info] [error]           } yield Resolver.Header(headerKey, headerValue)
[info] [error]                                              ^
[info] [error] four errors found
[info] [error] (Compile / compileIncremental) Compilation failed
[info] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
It fails to load the build because the [`csrConfiguration`](https://github.com/scala-steward-org/scala-steward/blob/3f7dfa96746a69b2935fd014b326f34afd9002d3/modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala#L67) task is not available in those old sbt versions.

### PR DESCRIPTION
**Pull request by fthomas**
This PR injects a sbt plugin into a repo's build that depends on the used sbt version. The main motivation of this change is to fix #2847.

The changes here are:
- the `sbt-plugin` project in the build is renamed to `sbt-plugin-1_3_11`. `1_3_11` is used as suffix because the plugin requires at least sbt 1.3.11, see #2858.
- a new `sbt-plugin-1_0_0` is added that contains a `StewardPlugin_1_0_0.scala` that is compatible with sbt 1.0.0 and above. It should also work with sbt 0.13.x but we don't test it here because I don't want to add Scala 2.10 to `crossScalaVersions`.
- `SbtAlg#getDependencies` first reads the sbt version from `build.properties` and then selects the appropriate plugin based on that version.

closes: #2847

### CODE REVIEW

**Comment by fthomas** [comment]
In a subsequent PR I'll move the sbt plugins into a separate repository (as has been done with the Mill plugin) to simplify our build.

**Review by exoego — APPROVED** [review]
